import type { Job, WorkerHit } from './types';
import { toISODate } from './types';

/**
 * 示範模式資料 —— 只在 Supabase 尚未設定時使用，
 * 目的是讓人第一次打開就看得到完整畫面，而不是空列表。
 */
function dayFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return toISODate(d);
}

const svc = (
  id: string,
  category_id: string,
  title: string | null,
  rate: number | null,
  rate_unit: 'hourly' | 'daily' | 'negotiable' = 'hourly',
) => ({ id, category_id, title, rate, rate_unit, note: null });

export const DEMO_WORKERS: WorkerHit[] = [
  {
    worker_id: 'demo-1',
    display_name: '小雲',
    avatar_url: null,
    bio: '教育系大四，帶過三個國中生數學。也常幫鄰居遛狗，狗狗都很喜歡我。',
    city: '臺北市',
    district: '中山區',
    rating_avg: 4.9,
    rating_count: 23,
    availability_id: 'demo-a1',
    avail_date: dayFromNow(1),
    start_time: '14:00:00',
    end_time: '18:00:00',
    services: [
      svc('s1', 'tutor', '國中數學家教', 520),
      svc('s2', 'dog_walk', null, 220),
      svc('s3', 'babysit', '有保母證照', 300),
    ],
  },
  {
    worker_id: 'demo-2',
    display_name: '阿哲',
    avatar_url: null,
    bio: '有自己的搬運推車跟小貨車，週末幾乎都有空。市場擺攤幫忙也很熟。',
    city: '臺北市',
    district: '大安區',
    rating_avg: 4.7,
    rating_count: 41,
    availability_id: 'demo-a2',
    avail_date: dayFromNow(1),
    start_time: '06:00:00',
    end_time: '12:00:00',
    services: [
      svc('s4', 'stall', '擺攤搬貨＋顧攤', 250),
      svc('s5', 'moving', null, 2400, 'daily'),
      svc('s6', 'carry', null, 280),
    ],
  },
  {
    worker_id: 'demo-3',
    display_name: 'Ingrid',
    avatar_url: null,
    bio: '前飯店房務主管，到府清潔十年經驗，自備清潔用品。',
    city: '新北市',
    district: '板橋區',
    rating_avg: 5.0,
    rating_count: 67,
    availability_id: 'demo-a3',
    avail_date: dayFromNow(2),
    start_time: '09:00:00',
    end_time: '17:00:00',
    services: [
      svc('s7', 'cleaning', '深度清潔・自備用品', 650),
      svc('s8', 'laundry', null, 400),
      svc('s9', 'declutter', null, 550),
    ],
  },
  {
    worker_id: 'demo-4',
    display_name: '阿嬤的好幫手 淑芬',
    avatar_url: null,
    bio: '照服員證照，主要接長輩陪伴與陪同就醫。開車接送沒問題。',
    city: '臺中市',
    district: '西屯區',
    rating_avg: 4.8,
    rating_count: 19,
    availability_id: 'demo-a4',
    avail_date: dayFromNow(3),
    start_time: '08:00:00',
    end_time: '16:00:00',
    services: [
      svc('s10', 'elder_care', '照服員證照', 400),
      svc('s11', 'hospital', '含交通接送', 450),
    ],
  },
  {
    worker_id: 'demo-5',
    display_name: 'Kai',
    avatar_url: null,
    bio: '接案攝影師，平日下午通常有空。活動紀錄、商品照都可以。',
    city: '高雄市',
    district: '苓雅區',
    rating_avg: 4.6,
    rating_count: 12,
    availability_id: 'demo-a5',
    avail_date: dayFromNow(2),
    start_time: '13:00:00',
    end_time: '19:00:00',
    services: [
      svc('s12', 'photo', '活動紀錄／商品照', null, 'negotiable'),
      svc('s13', 'video_edit', null, 800),
    ],
  },
  {
    worker_id: 'demo-6',
    display_name: '球球媽',
    avatar_url: null,
    bio: '家裡有三隻貓兩隻狗，很習慣照顧毛小孩。可到府或寄宿。',
    city: '臺北市',
    district: '文山區',
    rating_avg: 4.9,
    rating_count: 34,
    availability_id: 'demo-a6',
    avail_date: dayFromNow(1),
    start_time: '08:00:00',
    end_time: '20:00:00',
    services: [
      svc('s14', 'pet_sit', '可到府或寄宿', 800, 'daily'),
      svc('s15', 'dog_walk', null, 200),
      svc('s16', 'pet_drive', null, 350),
    ],
  },
];

export const DEMO_JOBS: (Job & { employer_name: string })[] = [
  {
    id: 'demo-j1',
    employer_id: 'demo-e1',
    employer_name: '寧夏夜市・阿發滷味',
    category_id: 'stall',
    title: '夜市顧攤＋出餐幫手',
    description: '週五週六人潮多，需要一個人幫忙裝袋、結帳。不用經驗，會教。',
    date: dayFromNow(2),
    start_time: '17:30:00',
    end_time: '23:30:00',
    city: '臺北市',
    district: '大同區',
    address_note: '寧夏路夜市中段',
    rate: 220,
    rate_unit: 'hourly',
    headcount: 2,
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-j2',
    employer_id: 'demo-e2',
    employer_name: '林太太',
    category_id: 'babysit',
    title: '週三下午顧小孩（4 歲）',
    description: '我要去複診大約三小時，孩子很好帶，家裡有玩具。希望有經驗者。',
    date: dayFromNow(4),
    start_time: '14:00:00',
    end_time: '17:00:00',
    city: '臺北市',
    district: '中山區',
    address_note: '近捷運行天宮站',
    rate: 320,
    rate_unit: 'hourly',
    headcount: 1,
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-j3',
    employer_id: 'demo-e3',
    employer_name: '陳先生',
    category_id: 'dog_walk',
    title: '出差五天，每天遛狗一次',
    description: '柴犬一隻，個性溫和。鑰匙可交付管理室。每天傍晚遛 40 分鐘。',
    date: dayFromNow(6),
    start_time: '18:00:00',
    end_time: '19:00:00',
    city: '新北市',
    district: '新店區',
    address_note: null,
    rate: 250,
    rate_unit: 'hourly',
    headcount: 1,
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-j4',
    employer_id: 'demo-e4',
    employer_name: '恆隆行・展場團隊',
    category_id: 'reception',
    title: '資訊展攤位接待（三天）',
    description: '負責發放 DM、引導參觀動線。需站立，供午餐。',
    date: dayFromNow(9),
    start_time: '09:30:00',
    end_time: '18:00:00',
    city: '臺北市',
    district: '信義區',
    address_note: '世貿一館',
    rate: 1800,
    rate_unit: 'daily',
    headcount: 6,
    status: 'open',
    created_at: new Date().toISOString(),
  },
];
